### ISSUE TITLE
Want to contribute 

### ISSUE THREAD

**Issue by douglasdcm** [pluscloudopen/openstack-image-crawler#13]
Hi, how are you? I found this project interesting. I'd like to contribute. Is it accepting MRs?

**Comment by frosty-geek** [comment]
Sure, be aware that there are plans to integrate this more closely with [osism/openstack-image-manager](https://github.com/osism/openstack-image-manager/issues/345) as part of [SovereignCloudStack/issues#168](https://github.com/SovereignCloudStack/issues/issues/168) and [DCO Sign-Off](https://developercertificate.org/) being mandatory
