### ISSUE TITLE
os var missing

### ISSUE THREAD

**Issue by linwalth** [pluscloudopen/openstack-image-crawler#19]
Seems like the historian is missing the os var import:

Further information: This is on MacOS.

```
./historian.py 
Traceback (most recent call last):
  File "/path/to/crawler/./historian.py", line 251, in <module>
    main()
  File "/path/to/crawler/./historian.py", line 206, in main
    config_filename = os.path.dirname(os.path.abspath(__file__)) + "etc/config.yaml"
                      ^^
NameError: name 'os' is not defined
```

**Comment by linwalth** [comment]
Addendum: After adding `import os` at the start of the historian i found that  "etc/config.yaml" in line 207 needs a slash for the path to form correctly like so: `    config_filename = os.path.dirname(os.path.abspath(__file__)) + "/etc/config.yaml"
`

**Comment by costelter** [comment]
I reverted to last known working version and added notfications for those distributions not supported by historian.
