### ISSUE TITLE
Please update install documentation to current github url

### ISSUE THREAD

**Issue by flashjmp** [pluscloudopen/openstack-image-crawler#27]
In the current readme.me the original (?) github repo seems to be reference instead of the current pluscloud open repo:

"git clone git@github.com:costelter/openstack-image-crawler.git"

**Comment by costelter** [comment]
Fixed. Thanks for reporting!

**Comment by costelter** [comment]
https://github.com/pluscloudopen/openstack-image-crawler/pull/29
